SEND_EMAIL="NO"
SEND_TELEGRAM="${NETDATA_ALERTS_SEND_TELEGRAM:-NO}"
TELEGRAM_BOT_TOKEN="${NETDATA_ALERTS_TELEGRAM_BOT_TOKEN:-}"
DEFAULT_RECIPIENT_TELEGRAM="${NETDATA_ALERTS_DEFAULT_RECIPIENT_TELEGRAM:-}"

role_recipients_telegram[sysadmin]="${NETDATA_ALERTS_DEFAULT_RECIPIENT_TELEGRAM:-}"
