"""Интеграция с WAPPI API."""

from app.services.wappi.client import (
    WappiAuth2FAResult,
    WappiAuthQrResult,
    WappiBalanceAddDaysResult,
    WappiClient,
    WappiClientError,
    WappiPlatform,
    WappiProfileCreateResult,
    WappiProfileDeleteResult,
    WappiProfileLogoutResult,
    WappiSyncMessageSendResult,
)
from app.services.wappi.binding import (
    ChannelProfileAlreadyBoundError,
    ChannelProfileBindingError,
    ChannelProfileConfigError,
    ChannelProfileExternalError,
    ChannelProfileNotBoundError,
    ChannelProfileUnsupportedTypeError,
    bind_profile_to_channel,
    build_wappi_client,
    request_channel_auth_qr,
    submit_channel_auth_2fa,
    unbind_profile_from_channel,
)

__all__ = [
    "WappiClient",
    "WappiClientError",
    "WappiPlatform",
    "WappiAuth2FAResult",
    "WappiAuthQrResult",
    "WappiBalanceAddDaysResult",
    "WappiProfileCreateResult",
    "WappiProfileDeleteResult",
    "WappiProfileLogoutResult",
    "WappiSyncMessageSendResult",
    "ChannelProfileAlreadyBoundError",
    "ChannelProfileBindingError",
    "ChannelProfileConfigError",
    "ChannelProfileExternalError",
    "ChannelProfileNotBoundError",
    "ChannelProfileUnsupportedTypeError",
    "bind_profile_to_channel",
    "build_wappi_client",
    "request_channel_auth_qr",
    "submit_channel_auth_2fa",
    "unbind_profile_from_channel",
]
